# Generated by Django 3.0 on 2020-03-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('bath', models.IntegerField(default=0)),
                ('squarefit', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
