# Generated by Django 3.0 on 2020-03-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200316_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hometype',
            field=models.CharField(max_length=50),
        ),
    ]
