# Generated by Django 3.0 on 2020-03-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_author_blogpost_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost_details',
            name='Timestamp',
        ),
    ]
