# Generated by Django 3.0 on 2020-03-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_blogpost_details_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost_details',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
