# Generated by Django 3.0 on 2020-03-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200319_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost_details',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
