# Generated by Django 3.0 on 2020-03-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20200319_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
